version: '3'

services:
  web:
    container_name: "bbtest"
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python -m smtpd -n -c DebuggingServer localhost:25 &
        python bbtest/bbtest/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
